package com.example.util

import androidx.compose.runtime.staticCompositionLocalOf
import com.example.data.model.MoodType
import com.example.data.model.WeatherType

enum class AppLanguage(val code: String, val displayName: String) {
    ZH("ZH", "简体中文"),
    EN("EN", "English");

    companion object {
        fun fromCode(code: String?): AppLanguage {
            return entries.firstOrNull { it.code.equals(code, ignoreCase = true) } ?: ZH
        }
    }
}

data class AppStrings(
    val isZh: Boolean,
    // App branding & generic
    val appName: String = "7Diary",
    val authorName: String = "Ziqi",
    val appSubtitle: String,
    val authorLabel: String,
    val versionLabel: String,
    val cancel: String,
    val save: String,
    val delete: String,
    val confirm: String,
    val edit: String,
    val share: String,
    val searchPlaceholder: String,
    val searchClear: String,
    val all: String,
    val today: String,
    val showAllEntries: String,
    val allMoods: String,
    val allWeathers: String,
    val favoritesOnly: String,
    val allEntries: String,
    val favorite: String,
    val unfavorite: String,

    // Navigation
    val navHome: String,
    val navCycle: String,
    val navTimeline: String,
    val navCalendar: String,
    val navAnalytics: String,
    val navSettings: String,

    // Home Screen
    val greetingMorning: String,
    val greetingAfternoon: String,
    val greetingEvening: String,
    val greetingNight: String,
    val homePromptSubtitle: String,
    val homePromptAction: String,
    val homePrompts: List<String>,
    val homeTodayStatus: String,
    val homeTodayLogged: String,
    val homeTodayNotYet: String,
    val homeRecentEntries: String,
    val homeViewAll: String,
    val homeEmptyPrompt: String,
    val homeEmptyAction: String,
    val homeCycleUnitBadge: String,
    val homeCycleBadgeFormatted: String,
    val homeNoCycle: String,

    // 7-Day Cycle View
    val cycleUnitTitle: String,
    val cycleUnitSubtitle: String,
    val cycleDayOfSeven: String,
    val cycleProgressLabel: String,
    val cycleCurrentBadge: String,
    val cycleReflectionTitle: String,
    val cycleReflectionSubtitle: String,
    val cycleReflectionPlaceholder: String,
    val cycleReflectionSave: String,
    val cycleReflectionSaved: String,
    val cycleRecordDayStory: String,
    val cycleLogDayEntry: String,
    val cycleDayPromptToday: String,
    val cycleDayPromptOther: String,
    val cycleSummaryCards: String,
    val cycleStationsTitle: String,
    val cycleCompletedCount: String,
    val cycleNumberLabel: String,
    val cycleCurrentTag: String,
    val cycleDaysCaps: String,
    val cycleGoalProgress: String,
    val cycleEntriesCount: String,
    val cyclePhotosCount: String,
    val cycleVoiceCount: String,
    val cycleCapsuleTitle: String,
    val cycleCapsuleSubtitle: String,
    val cycleEmotionalJourney: String,
    val cycleNoReflection: String,
    val cyclePhotoReel: String,
    val cycleReflectionDialogTitle: String,
    val cycleReflectionPrompt: String,
    val saveReflection: String,
    val cycleCompletedAllTitle: String,
    val cycleCompletedPaceTitle: String,
    val cycleCompletedCountTitle: String,
    val cycleFreshTitle: String,
    val cycleCompletedAllDesc: String,
    val cycleCompletedPaceDesc: String,
    val cycleCompletedCountDesc: String,
    val cycleFreshDesc: String,
    val cycleDayOfSevenBadge: String,

    // Timeline & Entries
    val timelineTitle: String,
    val timelineFilterMood: String,
    val timelineFilterWeather: String,
    val timelineNoEntries: String,
    val timelineNoEntriesFiltered: String,
    val timelineWordsCount: String,

    // Calendar
    val calendarTitle: String,
    val calendarSelectedDateEntries: String,
    val calendarNoEntriesOnDate: String,
    val calendarPrevMonth: String,
    val calendarNextMonth: String,

    // Analytics
    val analyticsTitle: String,
    val analyticsSubtitle: String,
    val analyticsTotalEntries: String,
    val analyticsTotalWords: String,
    val analyticsPhotos: String,
    val analyticsAudioNotes: String,
    val analyticsMoodDistribution: String,
    val analyticsMoodSubtitle: String,
    val analyticsWeatherDistribution: String,
    val analyticsWeatherSubtitle: String,
    val analyticsCycleCompletion: String,
    val analyticsPhotoGallery: String,
    val analyticsPhotoSubtitle: String,
    val analyticsNoPhotos: String,
    val analyticsWordsWritten: String,
    val analyticsStreakDays: String,
    val analyticsRecordedDays: String,
    val analyticsNoData: String,
    val analyticsTabStats: String,
    val analyticsTabGallery: String,
    val analyticsTabOneYearAgo: String,
    val analyticsMoodTab: String,
    val analyticsWeatherTab: String,

    // Settings
    val settingsTitle: String,
    val settingsSectionAppearance: String,
    val settingsThemeMode: String,
    val settingsThemeSystem: String,
    val settingsThemeLight: String,
    val settingsThemeDark: String,
    val settingsPaletteTitle: String,
    val settingsPaletteDynamicTitle: String = "Dynamic Material You",
    val settingsPaletteDynamicDesc: String,
    val settingsPaletteNothingTitle: String = "Nothing",
    val settingsPaletteNothingDesc: String,
    val settingsSectionLanguage: String,
    val settingsLanguageTitle: String,
    val settingsSectionSecurity: String,
    val settingsLockTitle: String,
    val settingsLockDesc: String,
    val settingsBiometricTitle: String,
    val settingsBiometricDesc: String,
    val settingsChangePin: String,
    val settingsSetPin: String,
    val settingsSectionAbout: String,
    val settingsAboutDesc: String,

    // Editor & Detail & Media
    val editorNewTitle: String,
    val editorEditTitle: String,
    val editorTitlePlaceholder: String,
    val editorContentPlaceholder: String,
    val editorSelectMood: String,
    val editorSelectWeather: String,
    val editorAddPhoto: String,
    val editorRecordAudio: String,
    val editorDeleteConfirmTitle: String,
    val editorDeleteConfirmMessage: String,
    val part1Title: String,
    val part2Title: String,
    val editorTitleLabel: String,
    val editorTabWrite: String,
    val editorTabPreview: String,
    val editorEmptyPreview: String,
    val ok: String,
    val todayMood: String,
    val todayWeather: String,
    val attachedPhotos: String,
    val addPhoto: String,
    val removePhoto: String,
    val voiceRecording: String,
    val recordVoiceNote: String,
    val recordingActive: String,
    val saveRecording: String,
    val discardRecording: String,
    val keepRecording: String,
    val heading: String,
    val bold: String,
    val italic: String,
    val strikethrough: String,
    val bulletList: String,
    val numberedList: String,
    val quote: String,

    // Lock & PIN Setup
    val lockIncorrectPin: String,
    val lockScreenTitle: String,
    val lockScreenSubtitle: String,
    val lockUnlockBiometric: String,
    val pinMismatch: String,
    val pinSetupTitle: String,
    val pinConfirmTitle: String,
    val pinSetupSubtitle: String,
    val pinConfirmSubtitle: String,

    // Additional Analytics & Media Localizations
    val analyticsTimeWeek: String = "近 7 天",
    val analyticsTimeMonth: String = "近 30 天",
    val analyticsTimeYear: String = "近 1 年",
    val analyticsTimeAll: String = "全部时间",
    val analyticsTimeRangeLabel: String = "时间范围",
    val analyticsTotalEntriesCount: String = "共 %d 篇日记",
    val analyticsNoEntriesPeriod: String = "所选时间段内暂无日记",
    val analyticsNoEntriesPeriodDesc: String = "切换到“全部时间”或在此时段内新建日记。",
    val analyticsMoodTitle: String = "心情统计",
    val analyticsMoodDesc: String = "心情分布与情绪趋势",
    val analyticsPrimaryMood: String = "主要心情: %s",
    val analyticsWeatherTitle: String = "天气统计",
    val analyticsWeatherDesc: String = "天气状况分布与模式",
    val analyticsPrimaryWeather: String = "主要天气: %s",
    val analyticsEntriesWithMood: String = "%s 心情日记 (%d)",
    val analyticsEntriesWithWeather: String = "%s 天气日记 (%d)",
    val analyticsPhotoCount: String = "%d 张照片",
    val analyticsFilterAllPhotos: String = "全部照片 (%d)",
    val analyticsFilterPast7Days: String = "近 7 天",
    val analyticsFilterPast30Days: String = "近 30 天",
    val analyticsNoPhotosInGallery: String = "画廊中暂无照片",
    val analyticsNoPhotosInPeriod: String = "所选时段内无照片",
    val analyticsNoPhotosDesc: String = "写日记时添加照片，画廊会自动汇总记录。",
    val analyticsNoPhotosPeriodDesc: String = "尝试切换筛选条件或写一篇带照片的日记。",
    val analyticsWritePhotoEntry: String = "写带图日记",
    val analyticsOneYearAgoTitle: String = "往年今日",
    val analyticsOneYearAgoDesc: String = "时光胶囊：重温1年前的今天记录的点滴",
    val analyticsTargetDate: String = "目标日期: %s",
    val analyticsBasedOnDate: String = "(基准日期: %s)",
    val analyticsPrevDay: String = "前一天",
    val analyticsNextDay: String = "后一天",
    val analyticsBackToToday: String = "回到今天",
    val analyticsMemoriesOnDate: String = "这一天的记忆 (%d)",
    val analyticsNoMemoriesOnDate: String = "这一天暂无日记记录",
    val analyticsNoMemoriesDesc: String = "你在 %s 这一天没有日记记录。\n你可以在下方补写这一天的回忆，或者写下今天的日记，让明年的今天可以重温！",
    val analyticsRecordMemoryForDate: String = "补写该日期的日记",
    val analyticsOpenFullEntry: String = "查看完整日记",
    val untitledEntry: String = "无标题日记",
    val close: String = "关闭",
    val play: String = "播放",
    val pause: String = "暂停",
    val deleteAudio: String = "删除语音"
)

val StringsZh = AppStrings(
    isZh = true,
    appSubtitle = "7天周期极简日记",
    authorLabel = "作者: Ziqi",
    versionLabel = "版本 1.0.0 • 离线 7-Day Journal",
    cancel = "取消",
    save = "保存",
    delete = "删除",
    confirm = "确定",
    edit = "编辑",
    share = "分享",
    searchPlaceholder = "搜索标题或正文内容...",
    searchClear = "清除搜索",
    all = "全部",
    today = "今天",
    showAllEntries = "查看全部日记",
    allMoods = "全部心情",
    allWeathers = "全部天气",
    favoritesOnly = "仅收藏",
    allEntries = "全部日记",
    favorite = "收藏",
    unfavorite = "取消收藏",

    navHome = "主页",
    navCycle = "7天周期",
    navTimeline = "时间轴",
    navCalendar = "日历",
    navAnalytics = "统计",
    navSettings = "设置",

    greetingMorning = "早上好",
    greetingAfternoon = "下午好",
    greetingEvening = "傍晚好",
    greetingNight = "夜深了",
    homePromptSubtitle = "点击立刻写下此刻想法",
    homePromptAction = "开始记录",
    homePrompts = listOf(
        "✨ 今天有什么瞬间让你心头一动？",
        "📝 记下今天的微光与感悟吧...",
        "🌧️ 今天的风吹过，留下了怎样的心情？",
        "☕ 停下一分钟，写两句送给未来的自己",
        "🌱 哪怕只是一句话，也是今天存在的印记",
        "🎧 听听周围的声音，今天发生了什么？",
        "💭 记录此刻的想法，让思绪落成文字",
        "☀️ 今天的阳光与心境，值得被珍藏"
    ),
    homeTodayStatus = "今日记录",
    homeTodayLogged = "已完成今日记录 ✨",
    homeTodayNotYet = "今日尚未记录，快来写一点吧",
    homeRecentEntries = "近期回忆",
    homeViewAll = "查看全部",
    homeEmptyPrompt = "还没有日记记录，记录下生活的第一个注脚吧",
    homeEmptyAction = "写第一篇日记",
    homeCycleUnitBadge = "7天周期",
    homeCycleBadgeFormatted = "第 %d 周期 • 第 %d/7 天",
    homeNoCycle = "暂无周期",

    cycleUnitTitle = "7天周期",
    cycleUnitSubtitle = "以 7 天为一个微周期，沉淀生活轨迹",
    cycleDayOfSeven = "第 %d 天 / 共 7 天",
    cycleProgressLabel = "本周周期完成度",
    cycleCurrentBadge = "当前周期",
    cycleReflectionTitle = "7天周期总结与思考",
    cycleReflectionSubtitle = "回顾这7天的起伏，为下个周期注入心力",
    cycleReflectionPlaceholder = "写下你对这7天周期的复盘与心境...",
    cycleReflectionSave = "保存思考",
    cycleReflectionSaved = "思考已保存",
    cycleRecordDayStory = "记录第 %d 天故事",
    cycleLogDayEntry = "补写第 %d 天记录",
    cycleDayPromptToday = "今天过得怎么样？记录天气与心境",
    cycleDayPromptOther = "点击为这天写下记录",
    cycleSummaryCards = "周期摘要",
    cycleStationsTitle = "7天旅程站点",
    cycleCompletedCount = "已完成 %d/7 天",
    cycleNumberLabel = "第 %d 周期",
    cycleCurrentTag = "当前",
    cycleDaysCaps = "天",
    cycleGoalProgress = "7天目标进度",
    cycleEntriesCount = "%d 篇日记",
    cyclePhotosCount = "%d 张照片",
    cycleVoiceCount = "%d 条语音",
    cycleCapsuleTitle = "7天故事胶囊",
    cycleCapsuleSubtitle = "周次回顾与反思",
    cycleEmotionalJourney = "7天情绪轨迹",
    cycleNoReflection = "本周7天周期尚未撰写周回顾。\n点击此处记录你的收获、感恩时刻或亮点！",
    cyclePhotoReel = "7天照片集 (%d)",
    cycleReflectionDialogTitle = "7天周期回顾",
    cycleReflectionPrompt = "回顾这7天：你完成了什么？什么给你带来了快乐？在下一个7天周期中你想改进什么？",
    saveReflection = "保存回顾",
    cycleCompletedAllTitle = "7天全部记录完成",
    cycleCompletedPaceTitle = "已记录 %d/7 天 • 进度很好",
    cycleCompletedCountTitle = "已记录 %d/7 天",
    cycleFreshTitle = "全新的7天周期已开启",
    cycleCompletedAllDesc = "本周7个篇章全部记录完成！你编织了一段完整的周度故事。",
    cycleCompletedPaceDesc = "已走过这个7天周期的过半旅程，每一刻都值得珍藏！",
    cycleCompletedCountDesc = "坚持每日记录，完成你的7天记忆胶囊。",
    cycleFreshDesc = "在这个7天记录单元中捕捉你的心情、天气与故事。",
    cycleDayOfSevenBadge = "第 %d 天（共7天）",

    timelineTitle = "时间轴",
    timelineFilterMood = "心情:",
    timelineFilterWeather = "天气:",
    timelineNoEntries = "暂无日记，点击右下方写一篇吧",
    timelineNoEntriesFiltered = "没有符合筛选条件的日记",
    timelineWordsCount = "%d 字",

    calendarTitle = "日历视图",
    calendarSelectedDateEntries = "选定日期的记录",
    calendarNoEntriesOnDate = "这一天还没有记录",
    calendarPrevMonth = "上一月",
    calendarNextMonth = "下一月",

    analyticsTitle = "统计与洞察",
    analyticsSubtitle = "发现你的情绪趋势与写作轨迹",
    analyticsTotalEntries = "日记总数",
    analyticsTotalWords = "累计字数",
    analyticsPhotos = "珍藏照片",
    analyticsAudioNotes = "语音备忘",
    analyticsMoodDistribution = "心情分布",
    analyticsMoodSubtitle = "记录的情绪轨迹与比重",
    analyticsWeatherDistribution = "天气分布",
    analyticsWeatherSubtitle = "日记中的晴雨记录",
    analyticsCycleCompletion = "7天周期达成率",
    analyticsPhotoGallery = "照片画廊",
    analyticsPhotoSubtitle = "日记中记录的珍贵瞬间",
    analyticsNoPhotos = "所选时间范围内暂无照片",
    analyticsWordsWritten = "记录字数",
    analyticsStreakDays = "连续记录",
    analyticsRecordedDays = "记录天数",
    analyticsNoData = "暂无统计数据，开始记录你的第一篇日记吧！",
    analyticsTabStats = "统计洞察",
    analyticsTabGallery = "照片墙",
    analyticsTabOneYearAgo = "往年今日",
    analyticsMoodTab = "心情",
    analyticsWeatherTab = "天气",

    settingsTitle = "设置",
    settingsSectionAppearance = "外观与主题",
    settingsThemeMode = "主题模式",
    settingsThemeSystem = "跟随系统",
    settingsThemeLight = "浅色模式",
    settingsThemeDark = "深色模式",
    settingsPaletteTitle = "色彩调色板",
    settingsPaletteDynamicDesc = "跟随系统壁纸取色 (Material You 动态色彩)",
    settingsPaletteNothingDesc = "极简黑白工业质感搭配经典红色强调点",
    settingsSectionLanguage = "语言 / Language",
    settingsLanguageTitle = "应用语言",
    settingsSectionSecurity = "隐私与安全",
    settingsLockTitle = "应用锁保护",
    settingsLockDesc = "使用 PIN 码保护你的私密日记",
    settingsBiometricTitle = "指纹 / 生物识别解锁",
    settingsBiometricDesc = "使用指纹或面容快速解锁",
    settingsChangePin = "更改 PIN 码",
    settingsSetPin = "设置 PIN 码",
    settingsSectionAbout = "关于应用",
    settingsAboutDesc = "本地离线存储，纯粹干净无追踪的 7 天周期日记本。",

    editorNewTitle = "新建日记",
    editorEditTitle = "编辑日记",
    editorTitlePlaceholder = "日记标题（可选）",
    editorContentPlaceholder = "写下此刻的想法，分享今天的点滴...",
    editorSelectMood = "选择心情",
    editorSelectWeather = "选择天气",
    editorAddPhoto = "添加照片",
    editorRecordAudio = "录制语音",
    editorDeleteConfirmTitle = "删除日记",
    editorDeleteConfirmMessage = "确定要永久删除这篇日记吗？此操作无法撤销。",
    part1Title = "基本信息",
    part2Title = "正文与媒体",
    editorTitleLabel = "日记标题",
    editorTabWrite = "撰写",
    editorTabPreview = "预览",
    editorEmptyPreview = "暂无内容，切换到“撰写”标签开始记录吧",
    ok = "确定",
    todayMood = "今日心情",
    todayWeather = "今日天气",
    attachedPhotos = "已附照片 (%d)",
    addPhoto = "添加照片",
    removePhoto = "移除照片",
    voiceRecording = "语音录音",
    recordVoiceNote = "录制语音日记",
    recordingActive = "录音中: %s",
    saveRecording = "保存录音",
    discardRecording = "放弃录音",
    keepRecording = "保留录音",
    heading = "标题",
    bold = "粗体",
    italic = "斜体",
    strikethrough = "删除线",
    bulletList = "无序列表",
    numberedList = "有序列表",
    quote = "引用",

    lockIncorrectPin = "密码错误，请重试",
    lockScreenTitle = "日记已加锁",
    lockScreenSubtitle = "输入4位密码查看日记",
    lockUnlockBiometric = "使用指纹解锁",
    pinMismatch = "两次输入的密码不一致，请重试",
    pinSetupTitle = "设置密码",
    pinConfirmTitle = "确认密码",
    pinSetupSubtitle = "输入4位数字作为日记密码",
    pinConfirmSubtitle = "请再次输入以确认密码"
)

val StringsEn = AppStrings(
    isZh = false,
    appSubtitle = "7-Day Cycle Minimal Journal",
    authorLabel = "Author: Ziqi",
    versionLabel = "Version 1.0.0 • Offline 7-Day Journal",
    cancel = "Cancel",
    save = "Save",
    delete = "Delete",
    confirm = "Confirm",
    edit = "Edit",
    share = "Share",
    searchPlaceholder = "Search title or content...",
    searchClear = "Clear search",
    all = "All",
    today = "Today",
    showAllEntries = "Show All Entries",
    allMoods = "All Moods",
    allWeathers = "All Weather",
    favoritesOnly = "Favorites Only",
    allEntries = "All Entries",
    favorite = "Favorite",
    unfavorite = "Unfavorite",

    navHome = "Home",
    navCycle = "7-Day Cycle",
    navTimeline = "Timeline",
    navCalendar = "Calendar",
    navAnalytics = "Analytics",
    navSettings = "Settings",

    greetingMorning = "Good morning",
    greetingAfternoon = "Good afternoon",
    greetingEvening = "Good evening",
    greetingNight = "Good night",
    homePromptSubtitle = "Tap to write your thoughts right now",
    homePromptAction = "Start Writing",
    homePrompts = listOf(
        "✨ What spark touched your heart today?",
        "📝 Capture today's little moments and thoughts...",
        "🌧️ What mood did today's breeze leave behind?",
        "☕ Pause for a minute, write a note to future you",
        "🌱 Even a single sentence marks today's story",
        "🎧 Listen to the world, what happened today?",
        "💭 Let your thoughts flow freely into words",
        "☀️ Today's sunshine and feelings deserve to be kept"
    ),
    homeTodayStatus = "Today's Entry",
    homeTodayLogged = "Today's story logged ✨",
    homeTodayNotYet = "Nothing logged yet today. Write a reflection!",
    homeRecentEntries = "Recent Memories",
    homeViewAll = "View All",
    homeEmptyPrompt = "No entries yet. Write your very first story!",
    homeEmptyAction = "Write First Entry",
    homeCycleUnitBadge = "7-Day Cycle",
    homeCycleBadgeFormatted = "Cycle #%d • Day %d/7",
    homeNoCycle = "No Cycle",

    cycleUnitTitle = "7-Day Cycle",
    cycleUnitSubtitle = "Anchor life in 7-day cyclical reflections",
    cycleDayOfSeven = "Day %d of 7",
    cycleProgressLabel = "Cycle Completion",
    cycleCurrentBadge = "Current",
    cycleReflectionTitle = "7-Day Unit Reflection",
    cycleReflectionSubtitle = "Review the past 7 days and gather strength for the next cycle",
    cycleReflectionPlaceholder = "Write your wrap-up thoughts for this 7-day cycle...",
    cycleReflectionSave = "Save Reflection",
    cycleReflectionSaved = "Reflection Saved",
    cycleRecordDayStory = "Record Day %d Story",
    cycleLogDayEntry = "Log Day %d Entry",
    cycleDayPromptToday = "How's your day going? Weather & thoughts",
    cycleDayPromptOther = "Fill in this day of your 7-day unit",
    cycleSummaryCards = "Cycle Summary",
    cycleStationsTitle = "7-Day Journey Stations",
    cycleCompletedCount = "%d/7 Completed",
    cycleNumberLabel = "Cycle #%d",
    cycleCurrentTag = "Current",
    cycleDaysCaps = "DAYS",
    cycleGoalProgress = "7-Day Goal Progress",
    cycleEntriesCount = "%d Entries",
    cyclePhotosCount = "%d Photos",
    cycleVoiceCount = "%d Voice",
    cycleCapsuleTitle = "7-Day Story Capsule",
    cycleCapsuleSubtitle = "Weekly Retrospective & Reflection",
    cycleEmotionalJourney = "Emotional Journey of the 7 Days",
    cycleNoReflection = "No weekly reflection written yet for this 7-day cycle.\nTap here to capture your takeaways, grateful moments, or highlights!",
    cyclePhotoReel = "7-Day Photo Reel (%d)",
    cycleReflectionDialogTitle = "7-Day Cycle Reflection",
    cycleReflectionPrompt = "Reflect on this 7-day period: What did you accomplish? What brought you joy? What would you like to improve in the next 7-day cycle?",
    saveReflection = "Save Reflection",
    cycleCompletedAllTitle = "7 of 7 Days Completed",
    cycleCompletedPaceTitle = "%d of 7 Days Logged • Great Pace",
    cycleCompletedCountTitle = "%d of 7 Days Logged",
    cycleFreshTitle = "A Fresh 7-Day Cycle Begins",
    cycleCompletedAllDesc = "All 7 chapters captured this week! You've woven a complete weekly story.",
    cycleCompletedPaceDesc = "Over halfway through this 7-day unit. Every moment matters!",
    cycleCompletedCountDesc = "Write daily to complete your 7-day memory collection.",
    cycleFreshDesc = "Track your mood, weather, and stories in this 7-day recording unit.",
    cycleDayOfSevenBadge = "Day %d of 7",

    timelineTitle = "Timeline",
    timelineFilterMood = "Mood:",
    timelineFilterWeather = "Weather:",
    timelineNoEntries = "No entries yet. Tap + to write your story",
    timelineNoEntriesFiltered = "No entries match your filters",
    timelineWordsCount = "%d words",

    calendarTitle = "Calendar View",
    calendarSelectedDateEntries = "Entries on Selected Date",
    calendarNoEntriesOnDate = "No entries on this date",
    calendarPrevMonth = "Previous Month",
    calendarNextMonth = "Next Month",

    analyticsTitle = "Analytics & Insights",
    analyticsSubtitle = "Discover your emotional trends and writing rhythm",
    analyticsTotalEntries = "Total Entries",
    analyticsTotalWords = "Total Words",
    analyticsPhotos = "Photos",
    analyticsAudioNotes = "Audio Notes",
    analyticsMoodDistribution = "Mood Distribution",
    analyticsMoodSubtitle = "Tracked emotional trajectory & proportion",
    analyticsWeatherDistribution = "Weather Distribution",
    analyticsWeatherSubtitle = "Weather observations in journal",
    analyticsCycleCompletion = "7-Day Cycle Rate",
    analyticsPhotoGallery = "Photo Gallery",
    analyticsPhotoSubtitle = "Precious captured visual moments",
    analyticsNoPhotos = "No photos found in selected time range",
    analyticsWordsWritten = "Words Written",
    analyticsStreakDays = "Streak Days",
    analyticsRecordedDays = "Recorded Days",
    analyticsNoData = "No data available. Start writing your first journal entry!",
    analyticsTabStats = "Insights",
    analyticsTabGallery = "Gallery",
    analyticsTabOneYearAgo = "On This Day",
    analyticsMoodTab = "Mood",
    analyticsWeatherTab = "Weather",

    settingsTitle = "Settings",
    settingsSectionAppearance = "Appearance & Theme",
    settingsThemeMode = "Theme Mode",
    settingsThemeSystem = "Follow System",
    settingsThemeLight = "Light Mode",
    settingsThemeDark = "Dark Mode",
    settingsPaletteTitle = "Color Palette",
    settingsPaletteDynamicDesc = "Harmonizes with device wallpaper & M3 dynamic tokens",
    settingsPaletteNothingDesc = "Industrial stark monochrome dot aesthetic with red accent",
    settingsSectionLanguage = "Language / 语言",
    settingsLanguageTitle = "App Language",
    settingsSectionSecurity = "Privacy & Security",
    settingsLockTitle = "App Lock Protection",
    settingsLockDesc = "Protect your private thoughts with a PIN passcode",
    settingsBiometricTitle = "Biometric / Fingerprint Unlock",
    settingsBiometricDesc = "Quickly unlock using fingerprint or face",
    settingsChangePin = "Change PIN Passcode",
    settingsSetPin = "Set PIN Passcode",
    settingsSectionAbout = "About 7Diary",
    settingsAboutDesc = "Local offline storage. Pure, private, tracker-free 7-day cyclical journal.",

    editorNewTitle = "New Entry",
    editorEditTitle = "Edit Entry",
    editorTitlePlaceholder = "Title (Optional)",
    editorContentPlaceholder = "Write your thoughts here, record what matters...",
    editorSelectMood = "Select Mood",
    editorSelectWeather = "Select Weather",
    editorAddPhoto = "Add Photos",
    editorRecordAudio = "Record Audio",
    editorDeleteConfirmTitle = "Delete Entry",
    editorDeleteConfirmMessage = "Are you sure you want to permanently delete this entry? This cannot be undone.",
    part1Title = "Basic Info",
    part2Title = "Content & Media",
    editorTitleLabel = "Entry Title",
    editorTabWrite = "Write",
    editorTabPreview = "Preview",
    editorEmptyPreview = "No content written yet. Switch to the 'Write' tab to begin writing.",
    ok = "OK",
    todayMood = "Today's Mood",
    todayWeather = "Today's Weather",
    attachedPhotos = "Attached Photos (%d)",
    addPhoto = "Add Photo",
    removePhoto = "Remove photo",
    voiceRecording = "Voice Recording",
    recordVoiceNote = "Record Voice Note",
    recordingActive = "Recording: %s",
    saveRecording = "Save Recording",
    discardRecording = "Discard Recording",
    keepRecording = "Keep Recording",
    heading = "Heading",
    bold = "Bold",
    italic = "Italic",
    strikethrough = "Strikethrough",
    bulletList = "Bulleted List",
    numberedList = "Numbered List",
    quote = "Quote",

    lockIncorrectPin = "Incorrect PIN. Try again.",
    lockScreenTitle = "Offline Diary Locked",
    lockScreenSubtitle = "Enter your 4-digit PIN to access your journal",
    lockUnlockBiometric = "Unlock with Fingerprint",
    pinMismatch = "PINs do not match. Please try again.",
    pinSetupTitle = "Create Passcode PIN",
    pinConfirmTitle = "Confirm Passcode PIN",
    pinSetupSubtitle = "Enter a 4-digit PIN for your diary",
    pinConfirmSubtitle = "Re-enter the 4-digit PIN to confirm",

    analyticsTimeWeek = "Past Week",
    analyticsTimeMonth = "Past Month",
    analyticsTimeYear = "Past Year",
    analyticsTimeAll = "All Time",
    analyticsTimeRangeLabel = "Time Range",
    analyticsTotalEntriesCount = "Total: %d entries",
    analyticsNoEntriesPeriod = "No Diary Entries in This Period",
    analyticsNoEntriesPeriodDesc = "Switch to 'All Time' or write a new entry during this period.",
    analyticsMoodTitle = "Mood Analytics",
    analyticsMoodDesc = "Distribution and emotional trends",
    analyticsPrimaryMood = "Primary: %s",
    analyticsWeatherTitle = "Weather Analytics",
    analyticsWeatherDesc = "Weather patterns and conditions",
    analyticsPrimaryWeather = "Primary: %s",
    analyticsEntriesWithMood = "Entries with %s Mood (%d)",
    analyticsEntriesWithWeather = "Entries on %s Days (%d)",
    analyticsPhotoCount = "%d Photos",
    analyticsFilterAllPhotos = "All Photos (%d)",
    analyticsFilterPast7Days = "Past 7 Days",
    analyticsFilterPast30Days = "Past 30 Days",
    analyticsNoPhotosInGallery = "No Photos in Gallery",
    analyticsNoPhotosInPeriod = "No Photos in This Period",
    analyticsNoPhotosDesc = "Add photos when writing entries, and your gallery will collect them automatically.",
    analyticsNoPhotosPeriodDesc = "Try switching the filter criteria or write a new illustrated entry.",
    analyticsWritePhotoEntry = "Write Photo Entry",
    analyticsOneYearAgoTitle = "On This Day",
    analyticsOneYearAgoDesc = "Time Capsule: Rediscover memories from exactly 1 year ago",
    analyticsTargetDate = "Target: %s",
    analyticsBasedOnDate = "(Based on: %s)",
    analyticsPrevDay = "Previous Day",
    analyticsNextDay = "Next Day",
    analyticsBackToToday = "Back to Today",
    analyticsMemoriesOnDate = "Memories on This Day (%d)",
    analyticsNoMemoriesOnDate = "No Memories on This Day",
    analyticsNoMemoriesDesc = "You don't have any diary entries for %s.\nYou can record a retrospective memory for this date below, or write today's diary so you have memories to look back on a year from now!",
    analyticsRecordMemoryForDate = "Record Memory for This Date",
    analyticsOpenFullEntry = "Open Full Diary Entry",
    untitledEntry = "Untitled Entry",
    close = "Close",
    play = "Play",
    pause = "Pause",
    deleteAudio = "Delete Audio"
)

val LocalAppStrings = staticCompositionLocalOf { StringsZh }

fun com.example.viewmodel.AnalyticsTimeRange.getLocalizedName(isZh: Boolean): String {
    return if (isZh) {
        when (this) {
            com.example.viewmodel.AnalyticsTimeRange.WEEK -> "近 7 天"
            com.example.viewmodel.AnalyticsTimeRange.MONTH -> "近 30 天"
            com.example.viewmodel.AnalyticsTimeRange.YEAR -> "近 1 年"
            com.example.viewmodel.AnalyticsTimeRange.ALL -> "全部时间"
        }
    } else {
        this.displayName
    }
}

fun MoodType.getLocalizedName(isZh: Boolean): String {
    return if (isZh) {
        when (this) {
            MoodType.JOYFUL -> "愉快"
            MoodType.HAPPY -> "开心"
            MoodType.CALM -> "平静"
            MoodType.EXCITED -> "兴奋"
            MoodType.NEUTRAL -> "平淡"
            MoodType.TIRED -> "疲惫"
            MoodType.SAD -> "难过"
            MoodType.ANGRY -> "生气"
        }
    } else {
        this.displayName
    }
}

fun WeatherType.getLocalizedName(isZh: Boolean): String {
    return if (isZh) {
        when (this) {
            WeatherType.SUNNY -> "晴天"
            WeatherType.CLOUDY -> "多云"
            WeatherType.PARTLY_CLOUDY -> "少云"
            WeatherType.RAINY -> "下雨"
            WeatherType.THUNDERSTORM -> "雷雨"
            WeatherType.SNOWY -> "下雪"
            WeatherType.WINDY -> "起风"
        }
    } else {
        this.displayName
    }
}
